apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-snip-cms-be
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
