apiVersion: v1
kind: Service
metadata:
  name: service-snip-cms-be
  namespace: development
spec:
  type: LoadBalancer
  selector:
    app: snip-cms-be
  ports:
    - protocol: TCP
      port: 8181
      targetPort: 3000
